server:
  port: 4001
spring:
  application:
    name: spring-cloud-config
  # 配置中心
  cloud:
    config:
      server:
        git:
          uri: ${config.repo.uri:https://github.com/zhourui392/spring-cloud-demo}
          searchPaths: spring-cloud-config-repo

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://zz:123456@localhost:2222/eureka/