---
spring:
  application:
      name: spring-cloud-provider
  zipkin:
    base-url: http://localhost:9000
server:
  port: 7779
management:
  security:
    enabled: false
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    status-page-url-path: /info
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 45
    lease-renewal-interval-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://zz:123456@localhost:2222/eureka/
    registry-fetch-interval-seconds: 30
info:
  build:
    artifact: @project.artifactId@
    groupId: @project.groupId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
