spring:
  application:
    name: spring-cloud-consumer
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: spring-cloud-config
  profiles:
    active: dev

server:
  port: 8886
  # 配置中心


# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://zz:123456@localhost:2222/eureka/